# Site settings
title: Moberg & Smoliak Wedding
email: twoten.ninth.ave@gmail.com
description: September 23rd, 2023
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.commoncause.is" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# Misc settings
featured-image-source:
sass:
    sass_dir: _sass

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
